env: "local" #dev, prod
storage_path: "./storage/db.db"
token_ttl: 1h
grpc:
  port: 44044
  timeout: 10h
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
