env: "local" #dev, prod
jwt_secret_key: "isfniuevouensviueniuvbeouvnsoinvosnvbosnoierbonsonvoisnvosnvodnbobvfndo"
grpc:
  port: 44044
  timeout: 10h
grpc_client:
  sending_service_address: "localhost:33033"
  jwt_service_address: "localhost:11011"
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
