services:
  postgres:
    image: postgres:17.2-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres        # Username for postgres datbase
      - POSTGRES_PASSWORD=postgres    # Password for postgres user
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local