// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: jwtsvc.proto

package jwtsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JWT_GenerateAccessToken_FullMethodName  = "/jwt.JWT/GenerateAccessToken"
	JWT_GenerateRefreshToken_FullMethodName = "/jwt.JWT/GenerateRefreshToken"
	JWT_ValidateAccessToken_FullMethodName  = "/jwt.JWT/ValidateAccessToken"
	JWT_ValidateRefreshToken_FullMethodName = "/jwt.JWT/ValidateRefreshToken"
	JWT_GenerateLink_FullMethodName         = "/jwt.JWT/GenerateLink"
)

// JWTClient is the client API for JWT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JWTClient interface {
	GenerateAccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	GenerateRefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenRequest, opts ...grpc.CallOption) (*ValidateAccessTokenResponse, error)
	ValidateRefreshToken(ctx context.Context, in *ValidateRefreshTokenRequest, opts ...grpc.CallOption) (*ValidateRefreshTokenResponse, error)
	GenerateLink(ctx context.Context, in *GenerateLinkRequest, opts ...grpc.CallOption) (*GenerateLinkResponse, error)
}

type jWTClient struct {
	cc grpc.ClientConnInterface
}

func NewJWTClient(cc grpc.ClientConnInterface) JWTClient {
	return &jWTClient{cc}
}

func (c *jWTClient) GenerateAccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, JWT_GenerateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) GenerateRefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, JWT_GenerateRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) ValidateAccessToken(ctx context.Context, in *ValidateAccessTokenRequest, opts ...grpc.CallOption) (*ValidateAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAccessTokenResponse)
	err := c.cc.Invoke(ctx, JWT_ValidateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) ValidateRefreshToken(ctx context.Context, in *ValidateRefreshTokenRequest, opts ...grpc.CallOption) (*ValidateRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRefreshTokenResponse)
	err := c.cc.Invoke(ctx, JWT_ValidateRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) GenerateLink(ctx context.Context, in *GenerateLinkRequest, opts ...grpc.CallOption) (*GenerateLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateLinkResponse)
	err := c.cc.Invoke(ctx, JWT_GenerateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWTServer is the server API for JWT service.
// All implementations must embed UnimplementedJWTServer
// for forward compatibility.
type JWTServer interface {
	GenerateAccessToken(context.Context, *AccessTokenRequest) (*AccessTokenResponse, error)
	GenerateRefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	ValidateAccessToken(context.Context, *ValidateAccessTokenRequest) (*ValidateAccessTokenResponse, error)
	ValidateRefreshToken(context.Context, *ValidateRefreshTokenRequest) (*ValidateRefreshTokenResponse, error)
	GenerateLink(context.Context, *GenerateLinkRequest) (*GenerateLinkResponse, error)
	mustEmbedUnimplementedJWTServer()
}

// UnimplementedJWTServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJWTServer struct{}

func (UnimplementedJWTServer) GenerateAccessToken(context.Context, *AccessTokenRequest) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessToken not implemented")
}
func (UnimplementedJWTServer) GenerateRefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRefreshToken not implemented")
}
func (UnimplementedJWTServer) ValidateAccessToken(context.Context, *ValidateAccessTokenRequest) (*ValidateAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAccessToken not implemented")
}
func (UnimplementedJWTServer) ValidateRefreshToken(context.Context, *ValidateRefreshTokenRequest) (*ValidateRefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRefreshToken not implemented")
}
func (UnimplementedJWTServer) GenerateLink(context.Context, *GenerateLinkRequest) (*GenerateLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateLink not implemented")
}
func (UnimplementedJWTServer) mustEmbedUnimplementedJWTServer() {}
func (UnimplementedJWTServer) testEmbeddedByValue()             {}

// UnsafeJWTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JWTServer will
// result in compilation errors.
type UnsafeJWTServer interface {
	mustEmbedUnimplementedJWTServer()
}

func RegisterJWTServer(s grpc.ServiceRegistrar, srv JWTServer) {
	// If the following call pancis, it indicates UnimplementedJWTServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JWT_ServiceDesc, srv)
}

func _JWT_GenerateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).GenerateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWT_GenerateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).GenerateAccessToken(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_GenerateRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).GenerateRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWT_GenerateRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).GenerateRefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_ValidateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).ValidateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWT_ValidateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).ValidateAccessToken(ctx, req.(*ValidateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_ValidateRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).ValidateRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWT_ValidateRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).ValidateRefreshToken(ctx, req.(*ValidateRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_GenerateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).GenerateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWT_GenerateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).GenerateLink(ctx, req.(*GenerateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JWT_ServiceDesc is the grpc.ServiceDesc for JWT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JWT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jwt.JWT",
	HandlerType: (*JWTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAccessToken",
			Handler:    _JWT_GenerateAccessToken_Handler,
		},
		{
			MethodName: "GenerateRefreshToken",
			Handler:    _JWT_GenerateRefreshToken_Handler,
		},
		{
			MethodName: "ValidateAccessToken",
			Handler:    _JWT_ValidateAccessToken_Handler,
		},
		{
			MethodName: "ValidateRefreshToken",
			Handler:    _JWT_ValidateRefreshToken_Handler,
		},
		{
			MethodName: "GenerateLink",
			Handler:    _JWT_GenerateLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwtsvc.proto",
}
