version: "3"

vars:
  CLIENTS: "GatewayAPI"

tasks:
  generate:
    aliases:
      - gen
    desc: "generates code from proto file to itself"
    cmds:
      - protoc -I protos protos/*.proto --go_out=./pb/usrdatasvc --go_opt=paths=source_relative --go-grpc_out=./pb/usrdatasvc --go-grpc_opt=paths=source_relative

  copy_proto:
    aliases:
      - copy
    desc: "Copy .proto files to clients"
    cmds:
      - echo Copying .proto files to clients...
      - |
        {{- $clients := split "," .CLIENTS }}
        {{- range $clients }}
        echo Creating directory ..\..\..\{{ . }}\api\grpccl\protos if not exists...
        powershell -Command "New-Item -ItemType Directory -Path '..\..\..\{{ . }}\api\grpccl\protos' -Force | Out-Null"
        
        echo Copying .proto files to ..\..\..\{{ . }}\api\grpccl\protos...
        powershell -Command "Copy-Item -Path 'protos\*.proto' -Destination '..\..\..\{{ . }}\api\grpccl\protos' -Force"
        {{- end }}
    silent: true

  generate_cl_pb:
    aliases:
      - genclpb
    desc: "Generate .pb.go files from .proto for clients"
    cmds:
      - echo Generating .pb.go files...
      - |
        {{- $clients := split "," .CLIENTS }}
        {{- range $clients }}
        echo Creating directory ..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc if not exists...
        powershell -Command "New-Item -ItemType Directory -Path '..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc' -Force | Out-Null"
        
        echo Removing old .pb.go files from ..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc...
        powershell -Command "Remove-Item -Path '..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc\*.pb.go' -Force -ErrorAction SilentlyContinue"
        
        echo Generating .pb.go files in ..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc...
        protoc -I '..\..\..\{{ . }}\api\grpccl\protos' '..\..\..\{{ . }}\api\grpccl\protos\usrdatasvc.proto' --go_out="..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc" --go_opt=paths=source_relative --go-grpc_out="..\..\..\{{ . }}\api\grpccl\pb\usrdatasvc" --go-grpc_opt=paths=source_relative
        {{- end }}
    silent: true

  update_clients:
    aliases:
      - updatecl
    desc: "updates clients pbs and protos"
    cmds:
      - task: gen
      - task: copy_proto
      - task: generate_cl_pb
    silent: true
