version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "generates code from proto file to itself"
    cmds:
      - protoc -I proto proto/*.proto --go_out=./pb --go_opt=paths=source_relative --go-grpc_out=./pb --go-grpc_opt=paths=source_relative