// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: usrdatasvc.proto

package usrdatasvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsrData_UpdBsUsrAttr_FullMethodName = "/usrdata.UsrData/UpdBsUsrAttr"
)

// UsrDataClient is the client API for UsrData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsrDataClient interface {
	UpdBsUsrAttr(ctx context.Context, in *UpdBsUsrAttrRequest, opts ...grpc.CallOption) (*UpdBsUsrAttrResponse, error)
}

type usrDataClient struct {
	cc grpc.ClientConnInterface
}

func NewUsrDataClient(cc grpc.ClientConnInterface) UsrDataClient {
	return &usrDataClient{cc}
}

func (c *usrDataClient) UpdBsUsrAttr(ctx context.Context, in *UpdBsUsrAttrRequest, opts ...grpc.CallOption) (*UpdBsUsrAttrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdBsUsrAttrResponse)
	err := c.cc.Invoke(ctx, UsrData_UpdBsUsrAttr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsrDataServer is the server API for UsrData service.
// All implementations must embed UnimplementedUsrDataServer
// for forward compatibility.
type UsrDataServer interface {
	UpdBsUsrAttr(context.Context, *UpdBsUsrAttrRequest) (*UpdBsUsrAttrResponse, error)
	mustEmbedUnimplementedUsrDataServer()
}

// UnimplementedUsrDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsrDataServer struct{}

func (UnimplementedUsrDataServer) UpdBsUsrAttr(context.Context, *UpdBsUsrAttrRequest) (*UpdBsUsrAttrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdBsUsrAttr not implemented")
}
func (UnimplementedUsrDataServer) mustEmbedUnimplementedUsrDataServer() {}
func (UnimplementedUsrDataServer) testEmbeddedByValue()                 {}

// UnsafeUsrDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsrDataServer will
// result in compilation errors.
type UnsafeUsrDataServer interface {
	mustEmbedUnimplementedUsrDataServer()
}

func RegisterUsrDataServer(s grpc.ServiceRegistrar, srv UsrDataServer) {
	// If the following call pancis, it indicates UnimplementedUsrDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsrData_ServiceDesc, srv)
}

func _UsrData_UpdBsUsrAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdBsUsrAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrDataServer).UpdBsUsrAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsrData_UpdBsUsrAttr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrDataServer).UpdBsUsrAttr(ctx, req.(*UpdBsUsrAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsrData_ServiceDesc is the grpc.ServiceDesc for UsrData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsrData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usrdata.UsrData",
	HandlerType: (*UsrDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdBsUsrAttr",
			Handler:    _UsrData_UpdBsUsrAttr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usrdatasvc.proto",
}
