// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: usrdatasvc.proto

package usrdatasvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BsUsr basic user attributes.
type BsUsrAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height        float64                `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BsUsrAttr) Reset() {
	*x = BsUsrAttr{}
	mi := &file_usrdatasvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BsUsrAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BsUsrAttr) ProtoMessage() {}

func (x *BsUsrAttr) ProtoReflect() protoreflect.Message {
	mi := &file_usrdatasvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BsUsrAttr.ProtoReflect.Descriptor instead.
func (*BsUsrAttr) Descriptor() ([]byte, []int) {
	return file_usrdatasvc_proto_rawDescGZIP(), []int{0}
}

func (x *BsUsrAttr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BsUsrAttr) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BsUsrAttr) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BsUsrAttr) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *BsUsrAttr) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

type UpdBsUsrAttrRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User  *BsUsrAttr             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// FieldMask, shows which fields should be updated.
	UpdMask       *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=upd_mask,json=updMask,proto3" json:"upd_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdBsUsrAttrRequest) Reset() {
	*x = UpdBsUsrAttrRequest{}
	mi := &file_usrdatasvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdBsUsrAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdBsUsrAttrRequest) ProtoMessage() {}

func (x *UpdBsUsrAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usrdatasvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdBsUsrAttrRequest.ProtoReflect.Descriptor instead.
func (*UpdBsUsrAttrRequest) Descriptor() ([]byte, []int) {
	return file_usrdatasvc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdBsUsrAttrRequest) GetUser() *BsUsrAttr {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdBsUsrAttrRequest) GetUpdMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdMask
	}
	return nil
}

type UpdBsUsrAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *BsUsrAttr             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdBsUsrAttrResponse) Reset() {
	*x = UpdBsUsrAttrResponse{}
	mi := &file_usrdatasvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdBsUsrAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdBsUsrAttrResponse) ProtoMessage() {}

func (x *UpdBsUsrAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usrdatasvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdBsUsrAttrResponse.ProtoReflect.Descriptor instead.
func (*UpdBsUsrAttrResponse) Descriptor() ([]byte, []int) {
	return file_usrdatasvc_proto_rawDescGZIP(), []int{2}
}

func (x *UpdBsUsrAttrResponse) GetUser() *BsUsrAttr {
	if x != nil {
		return x.User
	}
	return nil
}

var File_usrdatasvc_proto protoreflect.FileDescriptor

var file_usrdatasvc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x72, 0x64, 0x61, 0x74, 0x61, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x72, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01,
	0x0a, 0x09, 0x42, 0x73, 0x55, 0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x22, 0x74, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x42, 0x73, 0x55,
	0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73,
	0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x73, 0x55, 0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x5f, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d,
	0x61, 0x73, 0x6b, 0x52, 0x07, 0x75, 0x70, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x3e, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x42, 0x73, 0x55, 0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x73, 0x55,
	0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0x56, 0x0a, 0x07,
	0x55, 0x73, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x42, 0x73,
	0x55, 0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x72, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x55, 0x70, 0x64, 0x42, 0x73, 0x55, 0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x55, 0x70, 0x64, 0x42, 0x73, 0x55, 0x73, 0x72, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x73, 0x68, 0x61, 0x70, 0x65, 0x75, 0x70, 0x2e,
	0x75, 0x73, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x3b, 0x75, 0x73, 0x72, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usrdatasvc_proto_rawDescOnce sync.Once
	file_usrdatasvc_proto_rawDescData = file_usrdatasvc_proto_rawDesc
)

func file_usrdatasvc_proto_rawDescGZIP() []byte {
	file_usrdatasvc_proto_rawDescOnce.Do(func() {
		file_usrdatasvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_usrdatasvc_proto_rawDescData)
	})
	return file_usrdatasvc_proto_rawDescData
}

var file_usrdatasvc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_usrdatasvc_proto_goTypes = []any{
	(*BsUsrAttr)(nil),             // 0: usrdata.BsUsrAttr
	(*UpdBsUsrAttrRequest)(nil),   // 1: usrdata.UpdBsUsrAttrRequest
	(*UpdBsUsrAttrResponse)(nil),  // 2: usrdata.UpdBsUsrAttrResponse
	(*fieldmaskpb.FieldMask)(nil), // 3: google.protobuf.FieldMask
}
var file_usrdatasvc_proto_depIdxs = []int32{
	0, // 0: usrdata.UpdBsUsrAttrRequest.user:type_name -> usrdata.BsUsrAttr
	3, // 1: usrdata.UpdBsUsrAttrRequest.upd_mask:type_name -> google.protobuf.FieldMask
	0, // 2: usrdata.UpdBsUsrAttrResponse.user:type_name -> usrdata.BsUsrAttr
	1, // 3: usrdata.UsrData.UpdBsUsrAttr:input_type -> usrdata.UpdBsUsrAttrRequest
	2, // 4: usrdata.UsrData.UpdBsUsrAttr:output_type -> usrdata.UpdBsUsrAttrResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_usrdatasvc_proto_init() }
func file_usrdatasvc_proto_init() {
	if File_usrdatasvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usrdatasvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usrdatasvc_proto_goTypes,
		DependencyIndexes: file_usrdatasvc_proto_depIdxs,
		MessageInfos:      file_usrdatasvc_proto_msgTypes,
	}.Build()
	File_usrdatasvc_proto = out.File
	file_usrdatasvc_proto_rawDesc = nil
	file_usrdatasvc_proto_goTypes = nil
	file_usrdatasvc_proto_depIdxs = nil
}
