// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sending_service.proto

package sending_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sending_SendEmail_FullMethodName = "/registration.Sending/SendEmail"
)

// SendingClient is the client API for Sending service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendingClient interface {
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type sendingClient struct {
	cc grpc.ClientConnInterface
}

func NewSendingClient(cc grpc.ClientConnInterface) SendingClient {
	return &sendingClient{cc}
}

func (c *sendingClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, Sending_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendingServer is the server API for Sending service.
// All implementations must embed UnimplementedSendingServer
// for forward compatibility.
type SendingServer interface {
	SendEmail(context.Context, *EmailRequest) (*EmailResponse, error)
	mustEmbedUnimplementedSendingServer()
}

// UnimplementedSendingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSendingServer struct{}

func (UnimplementedSendingServer) SendEmail(context.Context, *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedSendingServer) mustEmbedUnimplementedSendingServer() {}
func (UnimplementedSendingServer) testEmbeddedByValue()                 {}

// UnsafeSendingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendingServer will
// result in compilation errors.
type UnsafeSendingServer interface {
	mustEmbedUnimplementedSendingServer()
}

func RegisterSendingServer(s grpc.ServiceRegistrar, srv SendingServer) {
	// If the following call pancis, it indicates UnimplementedSendingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sending_ServiceDesc, srv)
}

func _Sending_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendingServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sending_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendingServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sending_ServiceDesc is the grpc.ServiceDesc for Sending service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sending_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registration.Sending",
	HandlerType: (*SendingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Sending_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sending_service.proto",
}
